In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Resultant_CSV.csv")

In [3]:
type(df)
df.head()

id       age  hypertension  heart_disease  avg_glucose_level  \
0  0.123214  0.816895           0.0            1.0           0.801265   
1  0.708205  0.743652           0.0            0.0           0.679023   
2  0.426015  0.975586           0.0            1.0           0.234512   
3  0.824928  0.597168           0.0            0.0           0.536008   
4  0.021929  0.963379           1.0            0.0           0.549349   

        bmi  stroke  gender_Male  gender_Other  ever_married_Yes  ...  \
0  0.301260     1.0         True         False              True  ...   
1  0.212981     1.0        False         False              True  ...   
2  0.254296     1.0         True         False              True  ...   
3  0.276060     1.0        False         False              True  ...   
4  0.156930     1.0        False         False              True  ...   

   work_type_Private  work_type_Self-employed  work_type_children  \
0               True                    False               False   
1              False                     True               False   
2               True                    False               False   
3               True                    False               False   
4              False                     True               False   

   Residence_type_Urban  smoking_status_formerly smoked  \
0                  True                            True   
1                 False                           False   
2                 False                           False   
3                  True                           False   
4                 False                           False   

   smoking_status_never smoked  smoking_status_smokes  bmiCategory ageGroup  \
0                        False                  False  Underweight    Young   
1                         True                  False  Underweight    Young   
2                         True                  False  Underweight    Young   
3                        False                   True  Underweight    Young   
4                         True                  False  Underweight    Young   

  glucose_level_category  
0                    Low  
1                    Low  
2                    Low  
3                    Low  
4                    Low  

[5 rows x 21 columns]

In [4]:
df = pd.DataFrame(df)
df = df.drop(columns=['ageGroup', 'bmiCategory', 'glucose_level_category'])
df.head()

id       age  hypertension  heart_disease  avg_glucose_level  \
0  0.123214  0.816895           0.0            1.0           0.801265   
1  0.708205  0.743652           0.0            0.0           0.679023   
2  0.426015  0.975586           0.0            1.0           0.234512   
3  0.824928  0.597168           0.0            0.0           0.536008   
4  0.021929  0.963379           1.0            0.0           0.549349   

        bmi  stroke  gender_Male  gender_Other  ever_married_Yes  \
0  0.301260     1.0         True         False              True   
1  0.212981     1.0        False         False              True   
2  0.254296     1.0         True         False              True   
3  0.276060     1.0        False         False              True   
4  0.156930     1.0        False         False              True   

   work_type_Never_worked  work_type_Private  work_type_Self-employed  \
0                   False               True                    False   
1                   False              False                     True   
2                   False               True                    False   
3                   False               True                    False   
4                   False              False                     True   

   work_type_children  Residence_type_Urban  smoking_status_formerly smoked  \
0               False                  True                            True   
1               False                 False                           False   
2               False                 False                           False   
3               False                  True                           False   
4               False                 False                           False   

   smoking_status_never smoked  smoking_status_smokes  
0                        False                  False  
1                         True                  False  
2                         True                  False  
3                        False                   True  
4                         True                  False

In [5]:
df = df.applymap(lambda x: 1 if x else 0)
print(df)

      id  age  hypertension  heart_disease  avg_glucose_level  bmi  stroke  \
0      1    1             0              1                  1    1       1   
1      1    1             0              0                  1    1       1   
2      1    1             0              1                  1    1       1   
3      1    1             0              0                  1    1       1   
4      1    1             1              0                  1    1       1   
...   ..  ...           ...            ...                ...  ...     ...   
5105   1    1             1              0                  1    1       0   
5106   1    1             0              0                  1    1       0   
5107   1    1             0              0                  1    1       0   
5108   1    1             0              0                  1    1       0   
5109   1    1             0              0                  1    1       0   

      gender_Male  gender_Other  ever_married_Yes  work_type_Ne

In [6]:
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.feature_selection import chi2

In [19]:
X = df.iloc[:,0:11]
Y = df.iloc[:,-1]
bestfeatures = SelectKBest(score_func=chi2, k=1)
fit = bestfeatures.fit(X,Y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Columns','Chi-Score']  
print(featureScores)
X_new = fit.fit_transform(X,Y)
cols=featureScores[featureScores['Chi-Score']>10]['Columns']
X_new = pd.DataFrame(X_new,columns=cols)

print(X_new)

                   Columns  Chi-Score
0                       id   0.000036
1                      age   0.000143
2             hypertension   4.501022
3            heart_disease   9.379641
4        avg_glucose_level   0.000036
5                      bmi   0.000036
6                   stroke   0.388439
7              gender_Male   0.394505
8             gender_Other   0.182597
9         ever_married_Yes  19.454562
10  work_type_Never_worked   4.017126
Columns  ever_married_Yes
0                       1
1                       1
2                       1
3                       1
4                       1
...                   ...
5105                    1
5106                    1
5107                    1
5108                    1
5109                    1

[5110 rows x 1 columns]


In [20]:
X = df.drop(columns=['stroke']).values
y = df['stroke'].values 

In [ ]:
#Splitting the dataset into training and testing sets

In [22]:
from sklearn.model_selection import train_test_split
#80-20 train and test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
#75-25 train is again splitted to make Train and Validation in ratio of 75-25
X_train,X_val,y_train,y_val = train_test_split(X_train,y_train,test_size = 0.25,random_state=0)

In [24]:
#Balancing the dataset
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_train, y_train = smote.fit_resample(X_train, y_train)
X_test, y_test = smote.fit_resample(X_test, y_test)

print(f"X_train={X_train.shape}, y_train={y_train.shape}, X_test={X_test.shape}, y_test={y_test.shape}")

X_train=(5838, 17), y_train=(5838,), X_test=(1936, 17), y_test=(1936,)


Training the Logistic Regression Classifier

In [26]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(random_state = 0)
logistic.fit(X_train, y_train)

LogisticRegression(random_state=0)

Training the Random Forest Classifier

In [29]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion='entropy')
model.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

Predicting Logistic Regression Classifier

In [30]:
y_pred_logistic = logistic.predict(X_test)
print(np.concatenate((y_pred_logistic.reshape(len(y_pred_logistic),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [1 1]
 [1 1]
 [1 1]]


Predicting Random Forest Classifier

In [35]:
pred_y=model.predict(X_test)
print(np.concatenate((pred_y.reshape(len(pred_y),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [1 1]
 [0 1]]


Confusion Matrix and Accuracy Score for Logistic Regression Classifier

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, precision_score
cm = confusion_matrix(y_test, y_pred_logistic)
print(f"Confusion Matrix:\n {cm}")
print()
print(f"acccuracy: {accuracy_score(y_test, y_pred_logistic)}")

Confusion Matrix:
 [[486 482]
 [151 817]]

acccuracy: 0.6730371900826446


Confusion Matrix and Accuracy Score for Random Forest Classifier

In [38]:
cm = confusion_matrix(y_test, pred_y)
print(f"Confusion Matrix:\n {cm}")
print()
print(f"acccuracy: {accuracy_score(y_test, pred_y)}")

Confusion Matrix:
 [[587 381]
 [504 464]]

acccuracy: 0.5428719008264463
